id = "rich-vesper"
name = "Rich Vesper"
version = "0.0.3"
schema_version = 1
authors = [
    "Sergey Ukolov <zezic51@yandex.ru>",
    "bdsqqq <igorbedesqui@gmail.com>",
]
description = "Modified peppermint and orange flavored dark theme."
repository = "https://github.com/zezic/rich-vesper-zed"
